
Spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/demo_db
    username: postgres
    password: aremucoding
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
